name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install Rust
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      # Install ruff using git
      - name: Install ruff
        run: |
          git clone https://github.com/charliermarsh/ruff.git
          cd ruff
          cargo install --path .

      # Install Python packages
      - name: install packages
        run: make install

      # Lint with ruff
      - name: lint
        run: make lint

      # Run tests
      - name: test
        run: make test

      # Format with black
      - name: format
        run: make format

      # Deploy (if you have a deploy command in your Makefile)
      - name: deploy
        run: make deploy
