name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Install Python packages
      - name: install packages
        run: make install

      # Install ruff
      - name: Install ruff
        run: pip install ruff

      # Lint with ruff
      - name: lint
        run: make lint

      # Run tests
      - name: test
        run: make test

      # Format with black
      - name: format
        run: make format

      # Deploy (if you have a deploy command in your Makefile)
      - name: deploy
        run: make deploy
